name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '8.0.x'

      - name: Restore .NET dependencies
        run: dotnet restore backend/GitTraining.sln

      - name: Build .NET API
        run: dotnet build backend/GitTraining.sln --no-restore

      - name: Run .NET tests
        run: dotnet test backend/GitTraining.Api.Tests/GitTraining.Api.Tests.csproj

      - name: Publish .NET API
        run: dotnet publish backend/GitTraining.Api/GitTraining.Api.csproj -c Release -o publish/api

      - name: Upload .NET API artifact
        uses: actions/upload-artifact@v4
        with:
          name: gittraining-api
          path: publish/api
      
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '20'

      - name: Install Angular dependencies
        run: npm ci
        working-directory: frontend/git-training-ui

      - name: Build Angular
        run: npm run build
        working-directory: frontend/git-training-ui

      - name: Upload Angular artifact
        uses: actions/upload-artifact@v7
        with:
          name: gittraining-ui
          path: frontend/git-training-ui/dist/git-training-ui

